from . import student
from . import course
from . import faculty
from . import subject
from . import batch
from . import program
from . import program_level
from . import department
from . import academic_year
from . import academic_term
