{
    'name': 'Charge ERP Core',
    'version': '1.0',
    'summary': 'The base module for the Charge ERP School Management System',
    'author': 'Jules',
    'depends': ['base', 'mail'],
    'data': [
        'security/security.xml',
        'views/student_views.xml',
        'views/course_views.xml',
        'views/faculty_views.xml',
        'views/subject_views.xml',
        'views/batch_views.xml',
        'views/program_views.xml',
        'views/program_level_views.xml',
        'views/department_views.xml',
        'views/academic_year_views.xml',
        'views/academic_term_views.xml',
    ],
    'application': False,
    'installable': True,
}
